---
apiVersion: v1
kind: Pod
metadata:
  name: router-pod
spec:
  containers:
    - name: router
      image: docker.io/library/nginx:latest
      ports:
      - containerPort: 80
        hostPort: 8080
