---
apiVersion: v1
kind: Pod
metadata:
  name: router-pod
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
      - containerPort: 80
        hostPort: 8080
targetConfigs:
- name: gitops
  url: https://github.com/schlauerlauer/gitops
  kube:
  - name: kube-ex
    targetPath: fetchit/kube
    schedule: "*/1 * * * *"
  branch: main
